services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order-worker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
    depends_on:
      - rabbitmq

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3000" # Maps localhost:3001 to container:3000
    environment:
      RABBITMQ_URL: amqp://${RABBIT_USER}:${RABBIT_PASS}@rabbitmq:5672
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres
      - rabbitmq

  order-worker:
    build: ./order-worker
    container_name: order-worker
    command: npm run start:dev
    ports:
      - "3002:3000"
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
    depends_on:
      - rabbitmq
      - postgres

volumes:
  pgdata:
